version: '3'

services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    ports:
      - '8002:8002'
    volumes:
      - type: bind
        source: './data'
        target: '/custom_files'
